### ISSUE TITLE
Widget Tidak Tampil

### ISSUE THREAD

**Issue by agungsugiarto** [orapakat/ODC-THEMES#1]
Saya sudah melakukan config sesuai yang ada di readme.md tapi widget seperti gallery, slider dll tidak muncul. Bagaimana cara memunculkannya om @orapakat seperti yang ada di demo https://odc.orapakat.com ?

![screencapture-localhost-desa-index-php-first-2018-07-18-15_26_29](https://user-images.githubusercontent.com/10989147/42869516-75335eda-8a9f-11e8-9670-38537dea813a.png)

**Comment by orapakat** [comment]
mungkin bisa dicek album gallerynya apakah sudah ada.?
slider jg ambil dari albun galery



Sent from my Redmi Note 4On Agung Sugiarto <notifications@github.com>, 18 Jul 2018 3:30 pm wrote:Saya sudah melakukan config sesuai yang ada di readme.md tapi widget seperti gallery, slider dll tidak muncul. Bagaimana cara memunculkannya om @orapakat ?


—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/orapakat/ODC-THEMES","title":"orapakat/ODC-THEMES","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/orapakat/ODC-THEMES"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Widget Tidak Tampil (#1)"}],"action":{"name":"View Issue","url":"https://github.com/orapakat/ODC-THEMES/issues/1"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/orapakat/ODC-THEMES/issues/1",
"url": "https://github.com/orapakat/ODC-THEMES/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Widget Tidak Tampil (#1)",
"sections": [
{
"text": "",
"activityTitle": "**Agung Sugiarto**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@agungsugiarto",
"facts": [
{
"name": "Repository: ",
"value": "orapakat/ODC-THEMES"
},
{
"name": "Issue #: ",
"value": 1
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"orapakat/ODC-THEMES\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"orapakat/ODC-THEMES\",\n\"issueId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/orapakat/ODC-THEMES/issues/1"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 357607357\n}"
}
],
"themeColor": "26292E"
}
]
